# -*- coding: utf-8 -*-
"""CNN using pytorch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hm8XFoO68jv_ego46td7M9tx6_TCovZd
"""

!pip install optuna

import torch
import torch.nn as nn
import optuna
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

transform = transforms.ToTensor()
train_dataset = datasets.FashionMNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.FashionMNIST(root='./data', train=False, download=True, transform=transform)

class MyCNN(nn.Module):
    def __init__(self, conv1_out, conv2_out, dropout_rate):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(1, conv1_out, kernel_size=3, padding='same'),
            nn.BatchNorm2d(conv1_out),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),

            nn.Conv2d(conv1_out, conv2_out, kernel_size=3, padding='same'),
            nn.BatchNorm2d(conv2_out),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(conv2_out * 7 * 7, 128),
            nn.ReLU(),
            nn.Dropout(dropout_rate),
            nn.Linear(128, 10)
        )

    def forward(self, x):
        x = self.features(x)
        x = self.classifier(x)
        return x

# ---- objective is now OUTSIDE the class ----
def objective(trial):
    conv1_out = trial.suggest_categorical('conv1_out', [16, 32])
    conv2_out = trial.suggest_categorical('conv2_out', [32, 64])
    dropout_rate = trial.suggest_float('dropout_rate', 0.2, 0.5)
    learning_rate = trial.suggest_float('learning_rate', 1e-4, 1e-2, log=True)
    batch_size = trial.suggest_categorical('batch_size', [32, 64])
    epochs = trial.suggest_int('epochs', 3, 8)
    optimizer_name=trial.suggest_categorical('optimizer',['Adam','SGD','RMSprop'])

    train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
    test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

    model = MyCNN(conv1_out, conv2_out, dropout_rate).to(device)
    criterion = nn.CrossEntropyLoss()

    if optimizer_name == 'Adam':
        optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
    elif optimizer_name == 'SGD':
        optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)
    else:
        optimizer = torch.optim.RMSprop(model.parameters(), lr=learning_rate)

    for epoch in range(epochs):
        model.train()
        for batch_features, batch_labels in train_loader:
            batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)

            outputs = model(batch_features)
            loss = criterion(outputs, batch_labels)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

    model.eval()
    correct = 0
    total = 0
    with torch.no_grad():
        for batch_features, batch_labels in test_loader:
            batch_features, batch_labels = batch_features.to(device), batch_labels.to(device)
            outputs = model(batch_features)
            _, predicted = torch.max(outputs, 1)
            correct += (predicted == batch_labels).sum().item()
            total += batch_labels.shape[0]

    accuracy = correct / total
    print(f'Trial {trial.number}: Accuracy: {accuracy:.4f}')
    return accuracy

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)

print('Best trial:')
print(f'  Accuracy: {study.best_trial.value}')
print(f'  Params: {study.best_trial.params}')